name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  UUID: ${{ secrets.UUID }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        with:
          args: "secrets set UUID=${{ secrets.UUID }}"
        continue-on-error: true
      - uses: superfly/flyctl-actions@master
        with:
          args: "regions set hkg"
      - uses: superfly/flyctl-actions@master
        with:
          args: "deploy"
